### PR TITLE
GitHub Actions (Building and testing Java with Maven)

### PR DESCRIPTION
**Pull request by ayezan**
Mini Calculator App

Members:

Ayezan (se201003)
Ahad Ali (se201001)

### CODE REVIEW

**Comment by degr8sid-code** [comment]
Not enough detail. Refer to project1 branch for documentation guide.

**Comment by ayezan** [comment]
Ma'am jho bi issues ma apko kal tak dedo plzz kal tak ka time deda ap kal
hamara Database ka paper ha to abhi thora hard hojaiga

**Comment by degr8sid-code** [comment]
Still no update. Why?

**Comment by degr8sid-code** [comment]
Please reopen pull request so that I can accept it.

**Pull request closed without merging**
